// <auto-generated />
using System;
using System.Net;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwiftParcel.Domain.Enums;
using SwiftParcel.Infrastructure.Persistence;

#nullable disable

namespace SwiftParcel.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727133300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_action", new[] { "assign", "create", "delete", "escalate", "login_failed", "login_succeeded", "node_add", "permission_grant", "role_change", "status_change", "update" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_action", "audit_action", new[] { "create", "status_change", "assign", "update", "permission_grant", "login_failed", "login_succeeded", "role_change", "delete", "escalate", "node_add" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_status", new[] { "awaiting_customer", "cancelled", "closed", "escalated", "in_progress", "open", "resolved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_status", "case_status", new[] { "open", "in_progress", "awaiting_customer", "resolved", "closed", "escalated", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_type", new[] { "billing", "damaged", "delayed", "delivery_change", "lost", "other", "wrong_address" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_type", "case_type", new[] { "lost", "damaged", "delayed", "wrong_address", "billing", "delivery_change", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_channel", new[] { "chat", "email", "phone", "portal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_channel", "channel", new[] { "email", "phone", "chat", "portal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_day_of_week", new[] { "friday", "monday", "saturday", "sunday", "thursday", "tuesday", "wednesday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_day_of_week", "day_of_week", new[] { "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_entity_type", new[] { "auto_assignment_rule", "case", "customer", "email_template", "handler", "holiday", "note", "parcel", "region", "role", "sla_rule", "status_workflow", "system_config", "user", "user_permission" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_entity_type", "entity_type", new[] { "auto_assignment_rule", "note", "case", "customer", "email_template", "handler", "holiday", "parcel", "region", "role", "sla_rule", "status_workflow", "system_config", "user_permission", "user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_parcel_status", new[] { "damaged", "delivered", "delivery_attempt_failed", "in_transit", "lost", "out_for_delivery", "pending_pickup", "picked_up" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_parcel_status", "parcel_status", new[] { "pending_pickup", "picked_up", "in_transit", "out_for_delivery", "delivered", "delivery_attempt_failed", "lost", "damaged" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_priority", new[] { "critical", "high", "low", "medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_priority", "priority", new[] { "low", "medium", "high", "critical" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_service_type", new[] { "express", "same_day", "standard" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_service_type", "service_type", new[] { "standard", "express", "same_day" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_timeslot", new[] { "afternoon", "evening", "morning" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_timeslot", "timeslot", new[] { "morning", "afternoon", "evening" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwiftParcel.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<AuditAction>("AuditAction")
                        .HasColumnType("enum_action")
                        .HasColumnName("audit_action");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<EntityType>("EntityType")
                        .HasColumnType("enum_entity_type")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_stamp");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.AutoAssignmentRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignToDepartment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assign_to_department");

                    b.Property<int>("AssignToHandler")
                        .HasColumnType("integer")
                        .HasColumnName("assign_to_handler");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(99)
                        .HasColumnName("priority");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.HasKey("Id")
                        .HasName("pk_auto_assignment_rules");

                    b.ToTable("auto_assignment_rules", null, t =>
                        {
                            t.HasCheckConstraint("CK_auto_assignment_rules_priority", "priority >= 0 AND priority <= 99");
                        });
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_number");

                    b.Property<CaseType>("CaseType")
                        .HasColumnType("enum_case_type")
                        .HasColumnName("case_type");

                    b.Property<Channel>("Channel")
                        .HasColumnType("enum_channel")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EscalatedToId")
                        .HasColumnType("integer")
                        .HasColumnName("escalated_to_id");

                    b.Property<int?>("HandlerId")
                        .HasColumnType("integer")
                        .HasColumnName("handler_id");

                    b.Property<Priority>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum_priority")
                        .HasDefaultValue(Priority.Low)
                        .HasColumnName("priority");

                    b.Property<int>("Region")
                        .HasColumnType("integer")
                        .HasColumnName("region");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime>("ResolvedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_date");

                    b.Property<int>("SatisfactionScore")
                        .HasColumnType("integer")
                        .HasColumnName("satisfaction_score");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<CaseStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum_case_status")
                        .HasDefaultValue(CaseStatus.Open)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_cases_customer_id");

                    b.HasIndex("EscalatedToId")
                        .HasDatabaseName("ix_cases_escalated_to_id");

                    b.HasIndex("HandlerId")
                        .HasDatabaseName("ix_cases_handler_id");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.CaseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attachment");

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note_text");

                    b.HasKey("Id")
                        .HasName("pk_case_notes");

                    b.ToTable("case_notes", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.CaseParcel", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<int>("ParcelId")
                        .HasColumnType("integer")
                        .HasColumnName("parcel_id");

                    b.HasKey("CaseId", "ParcelId")
                        .HasName("pk_case_parcels");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("ix_case_parcels_parcel_id");

                    b.ToTable("case_parcels", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.CaseTag", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("CaseId", "TagId")
                        .HasName("pk_case_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_case_tags_tag_id");

                    b.ToTable("case_tags", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.HasKey("CountryCode")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<bool>("Vip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("vip");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_email");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.HasKey("Id")
                        .HasName("pk_email_templates");

                    b.HasIndex("TemplateName", "Language", "RegionId")
                        .IsUnique()
                        .HasDatabaseName("ix_email_templates_template_name_language_region_id");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Handler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<int>("MaxCases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_cases");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_handlers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_handlers_user_id");

                    b.ToTable("handlers", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("holiday_name");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_holidays");

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.HolidayRegion", b =>
                {
                    b.Property<int>("HolidayId")
                        .HasColumnType("integer")
                        .HasColumnName("holiday_id");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.HasKey("HolidayId", "RegionId")
                        .HasName("pk_holiday_regions");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_holiday_regions_region_id");

                    b.ToTable("holiday_regions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("DeclaredValueInEuros")
                        .HasColumnType("integer")
                        .HasColumnName("declared_value_in_euros");

                    b.Property<DateTime>("DeliveredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_date");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_address");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<ServiceType>("ServiceType")
                        .HasColumnType("enum_service_type")
                        .HasColumnName("service_type");

                    b.Property<ParcelStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum_parcel_status")
                        .HasDefaultValue(ParcelStatus.PendingPickup)
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_parcels");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_parcels_tracking_number");

                    b.ToTable("parcels", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Granular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("granular");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<DayOfWeek[]>("BusinessDays")
                        .IsRequired()
                        .HasColumnType("enum_day_of_week[]")
                        .HasColumnName("business_days");

                    b.Property<TimeOnly>("BusinessHoursEnd")
                        .HasColumnType("time")
                        .HasColumnName("business_hours_end");

                    b.Property<TimeOnly>("BusinessHoursStart")
                        .HasColumnType("time")
                        .HasColumnName("business_hours_start");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("manager_email");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region_name");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.HasIndex("RegionName")
                        .IsUnique()
                        .HasDatabaseName("ix_regions_region_name");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAccessAllRegions")
                        .HasColumnType("boolean")
                        .HasColumnName("can_access_all_regions");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_role_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.SlaRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<CaseType?>("CaseType")
                        .HasColumnType("enum_case_type")
                        .HasColumnName("case_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("EscalationAfter")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_after");

                    b.Property<string>("EscalationDepartment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("escalation_department");

                    b.Property<int>("EscalationHandlerId")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_handler_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBusinessHours")
                        .HasColumnType("boolean")
                        .HasColumnName("is_business_hours");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Priority?>("Priority")
                        .HasColumnType("enum_priority")
                        .HasColumnName("priority");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<ServiceType?>("ServiceType")
                        .HasColumnType("enum_service_type")
                        .HasColumnName("service_type");

                    b.Property<int>("SlaHours")
                        .HasColumnType("integer")
                        .HasColumnName("sla_hours");

                    b.HasKey("Id")
                        .HasName("pk_sla_rules");

                    b.ToTable("sla_rules", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.StatusWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<CaseStatus?>("FromStatus")
                        .HasColumnType("enum_case_status")
                        .HasColumnName("from_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("RequireNote")
                        .HasColumnType("boolean")
                        .HasColumnName("require_note");

                    b.Property<bool>("RequireResolution")
                        .HasColumnType("boolean")
                        .HasColumnName("require_resolution");

                    b.Property<CaseStatus?>("ToStatus")
                        .HasColumnType("enum_case_status")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_status_workflows");

                    b.ToTable("status_workflows", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.StatusWorkflowRole", b =>
                {
                    b.Property<int>("WorkflowId")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("WorkflowId", "RoleId")
                        .HasName("pk_status_workflow_roles");

                    b.ToTable("status_workflow_roles", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_key");

                    b.Property<JsonDocument>("ConfigValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_system_configs");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_system_configs_config_key");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_users_created_by_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.HasKey("UserId", "PermissionId")
                        .HasName("pk_user_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_user_permissions_permission_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.UserRegion", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.HasKey("UserId", "RegionId")
                        .HasName("pk_user_regions");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_user_regions_region_id");

                    b.ToTable("user_regions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Case", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cases_customers_customer_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Handler", "EscalatedTo")
                        .WithMany("CasesEscalatedTo")
                        .HasForeignKey("EscalatedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cases_handlers_escalated_to_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Handler", "Handler")
                        .WithMany("CasesHandled")
                        .HasForeignKey("HandlerId")
                        .HasConstraintName("fk_cases_handlers_handler_id");

                    b.Navigation("Customer");

                    b.Navigation("EscalatedTo");

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.CaseParcel", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_parcels_cases_case_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Parcel", "Parcel")
                        .WithMany()
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_parcels_parcels_parcel_id");

                    b.Navigation("Case");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.CaseTag", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_tags_cases_case_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_tags_tags_tag_id");

                    b.Navigation("Case");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.HolidayRegion", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Holiday", "Holiday")
                        .WithMany()
                        .HasForeignKey("HolidayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_regions_holidays_holiday_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_regions_regions_region_id");

                    b.Navigation("Holiday");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.User", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_permissions_permission_id");

                    b.HasOne("SwiftParcel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.UserRegion", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_regions_regions_region_id");

                    b.HasOne("SwiftParcel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_regions_users_user_id");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("SwiftParcel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Handler", b =>
                {
                    b.Navigation("CasesEscalatedTo");

                    b.Navigation("CasesHandled");
                });
#pragma warning restore 612, 618
        }
    }
}
