// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwiftParcel.Domain.Enums;
using SwiftParcel.Infrastructure.Persistence;

#nullable disable

namespace SwiftParcel.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_action", new[] { "assign", "create", "delete", "escalate", "login_failed", "login_succeeded", "note_add", "permission_grant", "role_change", "status_change", "update" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_action", "audit_action", new[] { "create", "status_change", "assign", "update", "permission_grant", "login_failed", "login_succeeded", "role_change", "delete", "escalate", "note_add" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_status", new[] { "awaiting_customer", "cancelled", "closed", "escalated", "in_progress", "open", "resolved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_status", "case_status", new[] { "open", "in_progress", "awaiting_customer", "resolved", "closed", "escalated", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_type", new[] { "billing", "damaged", "delayed", "delivery_change", "lost", "other", "wrong_address" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_case_type", "case_type", new[] { "lost", "damaged", "delayed", "wrong_address", "billing", "delivery_change", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_channel", new[] { "chat", "email", "phone", "portal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_channel", "channel", new[] { "email", "phone", "chat", "portal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_day_of_week", new[] { "friday", "monday", "saturday", "sunday", "thursday", "tuesday", "wednesday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_day_of_week", "day_of_week", new[] { "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_entity_type", new[] { "auto_assignment_rule", "case", "customer", "email_template", "handler", "holiday", "note", "parcel", "region", "role", "sla_rule", "status_workflow", "system_config", "user", "user_permission" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_entity_type", "entity_type", new[] { "auto_assignment_rule", "note", "case", "customer", "email_template", "handler", "holiday", "parcel", "region", "role", "sla_rule", "status_workflow", "system_config", "user_permission", "user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_parcel_status", new[] { "damaged", "delivered", "delivery_attempt_failed", "in_transit", "lost", "out_for_delivery", "pending_pickup", "picked_up" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_parcel_status", "parcel_status", new[] { "pending_pickup", "picked_up", "in_transit", "out_for_delivery", "delivered", "delivery_attempt_failed", "lost", "damaged" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_priority", new[] { "critical", "high", "low", "medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_priority", "priority", new[] { "low", "medium", "high", "critical" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_service_type", new[] { "express", "same_day", "standard" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_service_type", "service_type", new[] { "standard", "express", "same_day" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_timeslot", new[] { "afternoon", "evening", "morning" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum_timeslot", "timeslot", new[] { "morning", "afternoon", "evening" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseParcel", b =>
                {
                    b.Property<int>("CasesId")
                        .HasColumnType("integer")
                        .HasColumnName("cases_id");

                    b.Property<int>("ParcelsId")
                        .HasColumnType("integer")
                        .HasColumnName("parcels_id");

                    b.HasKey("CasesId", "ParcelsId")
                        .HasName("pk_case_parcel");

                    b.HasIndex("ParcelsId")
                        .HasDatabaseName("ix_case_parcel_parcels_id");

                    b.ToTable("case_parcel", (string)null);
                });

            modelBuilder.Entity("CaseTag", b =>
                {
                    b.Property<int>("CasesId")
                        .HasColumnType("integer")
                        .HasColumnName("cases_id");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer")
                        .HasColumnName("tags_id");

                    b.HasKey("CasesId", "TagsId")
                        .HasName("pk_case_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_case_tag_tags_id");

                    b.ToTable("case_tag", (string)null);
                });

            modelBuilder.Entity("RegionUser", b =>
                {
                    b.Property<int>("RegionsId")
                        .HasColumnType("integer")
                        .HasColumnName("regions_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasKey("RegionsId", "UsersId")
                        .HasName("pk_region_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_region_user_users_id");

                    b.ToTable("region_user", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<AuditAction>("AuditAction")
                        .HasColumnType("enum_action")
                        .HasColumnName("audit_action");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<EntityType>("EntityType")
                        .HasColumnType("enum_entity_type")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_stamp");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_number");

                    b.Property<CaseType>("CaseType")
                        .HasColumnType("enum_case_type")
                        .HasColumnName("case_type");

                    b.Property<Channel>("Channel")
                        .HasColumnType("enum_channel")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("HandlerId")
                        .HasColumnType("integer")
                        .HasColumnName("handler_id");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_escalated");

                    b.Property<Priority>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum_priority")
                        .HasDefaultValue(Priority.Low)
                        .HasColumnName("priority");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_date");

                    b.Property<int?>("SatisfactionScore")
                        .HasColumnType("integer")
                        .HasColumnName("satisfaction_score");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<CaseStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum_case_status")
                        .HasDefaultValue(CaseStatus.Open)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_cases_customer_id");

                    b.HasIndex("HandlerId")
                        .HasDatabaseName("ix_cases_handler_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_cases_region_id");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.CaseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attachment");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note_text");

                    b.HasKey("Id")
                        .HasName("pk_case_notes");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_case_notes_author_id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_notes_case_id");

                    b.ToTable("case_notes", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.HasKey("CountryCode")
                        .HasName("pk_countries");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<bool>("Vip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("vip");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "SwiftParcel.Domain.Entities.Customer.Address#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Address_CountryCode");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Address_StreetNumber");
                        });

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_email");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Handler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<int>("MaxCases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_cases");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_handlers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_handlers_user_id");

                    b.ToTable("handlers", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<float>("DeclaredValueInEuros")
                        .HasColumnType("real")
                        .HasColumnName("declared_value_in_euros");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_date");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<DateTime?>("PreferredPickupDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_pickup_date");

                    b.Property<Timeslot?>("PreferredPickupTimeslot")
                        .HasColumnType("enum_timeslot")
                        .HasColumnName("preferred_pickup_timeslot");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<ServiceType>("ServiceType")
                        .HasColumnType("enum_service_type")
                        .HasColumnName("service_type");

                    b.Property<ParcelStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum_parcel_status")
                        .HasDefaultValue(ParcelStatus.PendingPickup)
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RecipientAddress", "SwiftParcel.Domain.Entities.Parcel.RecipientAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Recipient_City");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Recipient_CountryCode");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Recipient_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Recipient_Street");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Recipient_StreetNumber");
                        });

                    b.HasKey("Id")
                        .HasName("pk_parcels");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_parcels_customer_id");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_parcels_tracking_number");

                    b.ToTable("parcels", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Granular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("granular");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permissions_role_id");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<DayOfWeek[]>("BusinessDays")
                        .IsRequired()
                        .HasColumnType("enum_day_of_week[]")
                        .HasColumnName("business_days");

                    b.Property<TimeOnly>("BusinessHoursEnd")
                        .HasColumnType("time")
                        .HasColumnName("business_hours_end");

                    b.Property<TimeOnly>("BusinessHoursStart")
                        .HasColumnType("time")
                        .HasColumnName("business_hours_start");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("manager_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_regions_country_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_regions_name");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAccessAllRegions")
                        .HasColumnType("boolean")
                        .HasColumnName("can_access_all_regions");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<int?>("StatusWorkflowId")
                        .HasColumnType("integer")
                        .HasColumnName("status_workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_role_name");

                    b.HasIndex("StatusWorkflowId")
                        .HasDatabaseName("ix_roles_status_workflow_id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.SlaRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<CaseType?>("CaseType")
                        .HasColumnType("enum_case_type")
                        .HasColumnName("case_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("EscalationAfter")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_after");

                    b.Property<string>("EscalationDepartment")
                        .HasColumnType("text")
                        .HasColumnName("escalation_department");

                    b.Property<int?>("EscalationHandlerId")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_handler_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBusinessHours")
                        .HasColumnType("boolean")
                        .HasColumnName("is_business_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Priority?>("Priority")
                        .HasColumnType("enum_priority")
                        .HasColumnName("priority");

                    b.Property<ServiceType?>("ServiceType")
                        .HasColumnType("enum_service_type")
                        .HasColumnName("service_type");

                    b.Property<int>("SlaHours")
                        .HasColumnType("integer")
                        .HasColumnName("sla_hours");

                    b.HasKey("Id")
                        .HasName("pk_sla_rules");

                    b.HasIndex("EscalationHandlerId")
                        .HasDatabaseName("ix_sla_rules_escalation_handler_id");

                    b.ToTable("sla_rules", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.StatusWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<CaseStatus?>("FromStatus")
                        .HasColumnType("enum_case_status")
                        .HasColumnName("from_status");

                    b.Property<bool>("RequireNote")
                        .HasColumnType("boolean")
                        .HasColumnName("require_note");

                    b.Property<bool>("RequireResolution")
                        .HasColumnType("boolean")
                        .HasColumnName("require_resolution");

                    b.Property<CaseStatus?>("ToStatus")
                        .HasColumnType("enum_case_status")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_status_workflows");

                    b.ToTable("status_workflows", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_key");

                    b.Property<JsonDocument>("ConfigValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_system_configs");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_system_configs_config_key");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_system_configs_updated_by_id");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_users_created_by_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CaseParcel", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Case", null)
                        .WithMany()
                        .HasForeignKey("CasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_parcel_cases_cases_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Parcel", null)
                        .WithMany()
                        .HasForeignKey("ParcelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_parcel_parcels_parcels_id");
                });

            modelBuilder.Entity("CaseTag", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Case", null)
                        .WithMany()
                        .HasForeignKey("CasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_tag_cases_cases_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_tag_tags_tags_id");
                });

            modelBuilder.Entity("RegionUser", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_region_user_regions_regions_id");

                    b.HasOne("SwiftParcel.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_region_user_users_users_id");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Case", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Customer", "Customer")
                        .WithMany("Cases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cases_customers_customer_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Handler", "Handler")
                        .WithMany("Cases")
                        .HasForeignKey("HandlerId")
                        .HasConstraintName("fk_cases_handlers_handler_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cases_regions_region_id");

                    b.Navigation("Customer");

                    b.Navigation("Handler");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.CaseNote", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_notes_users_author_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Case", "Case")
                        .WithMany("Notes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_notes_cases_case_id");

                    b.Navigation("Author");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Handler", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handlers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Parcel", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Customer", "Customer")
                        .WithMany("Parcels")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcels_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Permission", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_permissions_roles_role_id");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Region", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regions_countries_country_code");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Role", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.StatusWorkflow", null)
                        .WithMany("AllowedRoles")
                        .HasForeignKey("StatusWorkflowId")
                        .HasConstraintName("fk_roles_status_workflows_status_workflow_id");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.SlaRule", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.Handler", "EscalationHandler")
                        .WithMany()
                        .HasForeignKey("EscalationHandlerId")
                        .HasConstraintName("fk_sla_rules_handlers_escalation_handler_id");

                    b.Navigation("EscalationHandler");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.SystemConfig", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_configs_users_updated_by_id");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.User", b =>
                {
                    b.HasOne("SwiftParcel.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_users_created_by_id");

                    b.HasOne("SwiftParcel.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Case", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Handler", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SwiftParcel.Domain.Entities.StatusWorkflow", b =>
                {
                    b.Navigation("AllowedRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
