services:
  legacy-db:
    image: postgres:16
    environment:
      POSTGRES_DB: LegacySwiftParcelDb
      POSTGRES_USER: legacydb
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - legacy_data:/var/lib/postgresql/data
      - ./localenv/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U legacydb -d LegacySwiftParcelDb" ]
      interval: 3s
      timeout: 3s
      retries: 5

  swiftparcel-db:
    image: postgres:16
    environment:
        POSTGRES_DB: SwiftParcelDb
        POSTGRES_USER: swiftparceldb
        POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - swiftparcel_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U swiftparceldb -d SwiftParcelDb" ]
      interval: 3s
      timeout: 3s
      retries: 5

  backoffice-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_SYSTEM_NET_DISABLEIPV6=1
      - ConnectionStrings__Legacy=Host=legacy-db;Database=LegacySwiftParcelDb;Username=legacydb;Password=password
      - ConnectionStrings__SwiftParcel=Host=swiftparcel-db;Database=SwiftParcelDb;Username=swiftparceldb;Password=password
    depends_on:
      legacy-db:
        condition: service_healthy
      swiftparcel-db:
        condition: service_healthy
        
volumes:
    legacy_data:
    swiftparcel_data: